---
# tasks file for docker
- name: create image docker 
  docker image:
     name: devops 
     build: 
       path: /var/lib/jenkins/workspace/devops 
       pull: no 
     source: build 
     state: present
     force source: true 
- name: run container docker 
  docker container:
     name: myapp-container 
     image: devops:latest 
     state: started 
     recreate: true 
     ports: 
        - "4200:80"
